### ISSUE TITLE
[suggest] 재료 데이터 수정 후 메뉴 리스트로 돌아가기

### ISSUE THREAD

**Issue by WoongZ** [ColorOfLight/cs374-food-for-thought#29]
현재 재료 데이터를 수정한 다음에는 메뉴 리스트 페이지가 아닌 해당 메뉴의 상세보기 페이지로 돌아가고 있습니다. 저는 메뉴 리스트로 돌아가는 게 맞지 않나 싶네요.

**Comment by SeongKwonHa** [comment]
음...저는 상세페이지에서 들어가서 고쳤다면 다시 상세페이지로 가는게 맞다고 생각하긴하는데.. 성호씨와 얘기한번해보죠!

**Comment by ColorOfLight** [comment]
추가적인 피드백이 없으면 상세로 돌아가는 게 맞다고 생각해서 일단은 그대로 놔두는 게 좋을 거 같습니다
